### PR TITLE
Add `random-boolean` to readme

### PR DESCRIPTION
**Pull request by arthurvr**
https://github.com/sindresorhus/random-float/commit/8affeb2f4880b81fdc62aba9aa597e4d7d657c4f#commitcomment-11894597

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you place it below `random-item`? It's sorted by how often I would use them.

Also feel free to commit directly for smaller changes like this.

**Comment by arthurvr** [comment]
> Can you place it below random-item? It's sorted by how often I would use them.

Sure.

> Also feel free to commit directly for smaller changes like this.

I don't have push access to this repo (yet)

**Comment by sindresorhus** [comment]
Oh, right. You do now.

**Comment by arthurvr** [comment]
We need something to automate that too :) Thanks! I'll take care of this.

**Pull request closed without merging**
